# Project info
site_name: IBM Bob Level 3
site_description: IBM Bob Level 3
site_author: Christopher Bienko (cdbienko@us.ibm.com)
copyright: Copyright &copy; 2026 IBM

# Repository
repo_name: IBM/bob-l3
#repo_url: https://github.com/IBM/bob-l3
#edit_uri: edit/master/docs
docs_dir: docs

nav:
  - Introduction: 'index.md'
  - Setup: 'setup.md'
  - 1. Assist:
    - Literate Coding | Editing with intent: assist/1-1.md
  - 2. Delegate:
    - The Agentic Sidebar | From assistant to partner: delegate/2-1.md
    - Applying Agentic Modes | Implementing seat classes in Galaxium Travels: delegate/2-2.md
  - 3. Tailor:
    - init & agents.md | Teaching Bob your codebase: tailor/3-1.md
    - Bob Rules | Encoding your standards: tailor/3-2.md
    - Custom Modes | Shaping Bob to every role: tailor/3-3.md
  - 4. Scale & Extend:
    - The Context Window | Keeping Bob reliable at scale: scale/4-1.md
    - Bob Shell | Moving beyond the IDE: scale/4-2.md
    - Extending with MCP | Connecting Bob to everything: scale/4-3.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
  palette:
      scheme: default
  color_mode: auto

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
  - macros
  - search
  - glightbox
  - print-site:
      add_to_navigation: false
      print_page_title: 'IBM watsonx Code Assistant Level 4 Lab Guide'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: false
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: false
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

markdown_extensions:
  - markdown_fenced_code_tabs
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables

extra_css:
  - styles/override-print.css

extra_javascript:
  - _static/hide-toc-nav.js